log_level: debug

tunnel: grpcs://127.0.0.1:1443
# tunnel: grpcs://127.0.0.1:1443
# tunnel: http2://127.0.0.1:1443/h2
# tunnel: wss://127.0.0.1:1443/ws
local_address: 0.0.0.0:8488
cert_file: ./testdata/server.pem
key_file: ./testdata/server.key
